// game-master/shadow_lob.hpp
// Shadow Book Validator — out-of-band correctness engine
//
// Runs a second, independent LOB that replays every order and fill
// generated by the live PersistentLOB, then verifies:
//   1. FIFO price-time priority (no order at seq N matched before N-1 at same price)
//   2. No double-fills (same order filled more than its volume)
//   3. No stale cancels (cancelling an already-filled or non-existent order)
//   4. Cash balance integrity (total buys × prices = total cash debited)
//   5. Fill price validity (market buy must fill at ask or better; sell at bid or better)
//
// Called asynchronously from the Watchdog thread (Core 4) via the TelemetryRing.
// Scoring penalty: each violation type subtracts from the correctness_score (0.0–1.0).

#pragma once
#include <cstdint>
#include <map>
#include <deque>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <string>
#include <sstream>
#include <atomic>
#include <mutex>
#include <algorithm>
#include "rendezvous.hpp"

// ─── Violation types ───────────────────────────────────────────────────────
enum class ViolationType : uint8_t {
    FIFO_PRIORITY_BREACH     = 0,  // older order at same price level was skipped
    DOUBLE_FILL              = 1,  // order filled beyond its original volume
    STALE_CANCEL             = 2,  // cancel on non-existent or already-filled order
    FILL_PRICE_INVALID       = 3,  // fill price worse than best available
    CASH_INTEGRITY_MISMATCH  = 4,  // computed cash != reported cash
    POSITION_INTEGRITY_MISMATCH = 5,
};

struct Violation {
    ViolationType type;
    int64_t       tick_id;
    uint64_t      order_id;
    std::string   detail;
};

// ─── Shadow order record ───────────────────────────────────────────────────
struct ShadowOrder {
    uint64_t  order_id;
    uint64_t  sequence_num;   // global insertion sequence (for FIFO check)
    int64_t   price_fp;
    int64_t   original_volume;
    int64_t   remaining_volume;
    bool      is_bid;
    bool      is_cancelled  = false;
    bool      is_fully_filled = false;
    int64_t   tick_added;
};

// ─── Shadow price level (FIFO deque, same structure as live LOB) ──────────
struct ShadowLevel {
    std::deque<uint64_t> order_ids;  // FIFO: front = oldest sequence = matched first
    int64_t              total_volume = 0;
};

// ─── Shadow LOB ───────────────────────────────────────────────────────────
class ShadowLOB {
public:
    // Scoring weights (sum to 1.0)
    static constexpr double W_FIFO     = 0.35;
    static constexpr double W_DOUBLE   = 0.25;
    static constexpr double W_CANCEL   = 0.10;
    static constexpr double W_PRICE    = 0.20;
    static constexpr double W_CASH     = 0.10;

    // Penalty per violation (capped at weight)
    static constexpr double PENALTY_PER_FIFO   = 0.01;
    static constexpr double PENALTY_PER_DOUBLE = 0.02;
    static constexpr double PENALTY_PER_CANCEL = 0.005;
    static constexpr double PENALTY_PER_PRICE  = 0.015;
    static constexpr double PENALTY_PER_CASH   = 0.05;

    int64_t shadow_best_bid_   = 0;
    int64_t shadow_best_ask_   = INT64_MAX;
    int64_t shadow_last_trade_fp_ = 0;
    int64_t shadow_position_   = 0;
    __int128 shadow_cash_fp_   = static_cast<__int128>(to_fp(100'000.0));
    int32_t contestant_fills_  = 0;

    ShadowLOB() = default;

    // ── API: called by GM to replay every action into the shadow book ──────

    // Record a limit order placement (called when add_limit() succeeds in live LOB)
    void on_limit_add(bool is_bid, int64_t price_fp, int64_t volume,
                      int32_t participant, uint64_t order_id, int64_t tick_id) {
        std::lock_guard<std::mutex> lock(mu_);
        uint64_t seq = ++global_seq_;
        ShadowOrder so{
            .order_id        = order_id,
            .sequence_num    = seq,
            .price_fp        = price_fp,
            .original_volume = volume,
            .remaining_volume = volume,
            .is_bid          = is_bid,
            .tick_added      = tick_id,
        };
        orders_[order_id] = so;

        if (is_bid) {
            auto& level = bid_levels_[price_fp];
            level.order_ids.push_back(order_id);
            level.total_volume += volume;
        } else {
            auto& level = ask_levels_[price_fp];
            level.order_ids.push_back(order_id);
            level.total_volume += volume;
        }

        if (is_bid && price_fp > shadow_best_bid_) shadow_best_bid_ = price_fp;
        if (!is_bid && price_fp < shadow_best_ask_) shadow_best_ask_ = price_fp;
    }

    // Record a fill (called once per MatchedFill from live LOB)
    void on_fill(const MatchedFill& f, uint64_t maker_order_id, int64_t tick_id) {
        std::lock_guard<std::mutex> lock(mu_);

        // ── 1. Fill price validity ─────────────────────────────────────────
        if (f.taker_is_buy) {
            // Buy taker must fill at shadow_best_ask_ or better (lower price)
            if (f.price_fp > shadow_best_ask_ + to_fp(0.01)) {
                add_violation({ViolationType::FILL_PRICE_INVALID, tick_id, maker_order_id,
                    "buy fill price " + fp_str(f.price_fp) + " > best ask " + fp_str(shadow_best_ask_)});
                penalty_price_ = std::min(W_PRICE, penalty_price_ + PENALTY_PER_PRICE);
            }
        } else {
            // Sell taker must fill at shadow_best_bid_ or better (higher price)
            if (f.price_fp < shadow_best_bid_ - to_fp(0.01)) {
                add_violation({ViolationType::FILL_PRICE_INVALID, tick_id, maker_order_id,
                    "sell fill price " + fp_str(f.price_fp) + " < best bid " + fp_str(shadow_best_bid_)});
                penalty_price_ = std::min(W_PRICE, penalty_price_ + PENALTY_PER_PRICE);
            }
        }

        // ── 2. Double-fill / volume integrity ─────────────────────────────
        shadow_last_trade_fp_ = f.price_fp;
        auto it = orders_.find(maker_order_id);
        if (it != orders_.end()) {
            ShadowOrder& so = it->second;
            if (so.is_cancelled) {
                add_violation({ViolationType::DOUBLE_FILL, tick_id, maker_order_id,
                    "fill on already-cancelled order"});
                penalty_double_ = std::min(W_DOUBLE, penalty_double_ + PENALTY_PER_DOUBLE);
            } else if (f.volume > so.remaining_volume) {
                add_violation({ViolationType::DOUBLE_FILL, tick_id, maker_order_id,
                    "overfill: fill " + std::to_string(f.volume)
                    + " > remaining " + std::to_string(so.remaining_volume)});
                penalty_double_ = std::min(W_DOUBLE, penalty_double_ + PENALTY_PER_DOUBLE);
            }

            // ── 3. FIFO priority check ────────────────────────────────────
            bool found_older = false;
            uint64_t front_id = 0;
            if (so.is_bid) {
                auto lit = bid_levels_.find(so.price_fp);
                if (lit != bid_levels_.end() && !lit->second.order_ids.empty()) {
                    found_older = true;
                    front_id = lit->second.order_ids.front();
                }
            } else {
                auto lit = ask_levels_.find(so.price_fp);
                if (lit != ask_levels_.end() && !lit->second.order_ids.empty()) {
                    found_older = true;
                    front_id = lit->second.order_ids.front();
                }
            }
            if (found_older) {
                if (front_id != maker_order_id) {
                    // There's an older order at this price that should have been matched first
                    auto front_it = orders_.find(front_id);
                    if (front_it != orders_.end() &&
                        front_it->second.sequence_num < so.sequence_num &&
                        !front_it->second.is_cancelled) {
                        add_violation({ViolationType::FIFO_PRIORITY_BREACH, tick_id, maker_order_id,
                            "order " + std::to_string(maker_order_id)
                            + " filled before older order " + std::to_string(front_id)
                            + " at price " + fp_str(so.price_fp)});
                        penalty_fifo_ = std::min(W_FIFO, penalty_fifo_ + PENALTY_PER_FIFO);
                    }
                }
            }

            // Apply fill
            so.remaining_volume -= f.volume;
            if (so.remaining_volume <= 0) {
                so.is_fully_filled = true;
                _remove_from_level(maker_order_id, so);
                orders_.erase(it);
                _update_best();
            }
        } else {
            add_violation({ViolationType::DOUBLE_FILL, tick_id, maker_order_id,
                "fill on unknown or already fully-filled order"});
            penalty_double_ = std::min(W_DOUBLE, penalty_double_ + PENALTY_PER_DOUBLE);
        }

        // ── 4. Cash & position tracking for contestant fills ──────────────
        if (f.taker_participant == CONTESTANT || f.maker_participant == CONTESTANT) {
            bool c_buy = (f.taker_is_buy && f.taker_participant == CONTESTANT) ||
                         (!f.taker_is_buy && f.maker_participant == CONTESTANT);
            int64_t sign = c_buy ? +1 : -1;
            shadow_position_   += sign * f.volume;
            shadow_cash_fp_    -= sign * f.volume * f.price_fp;
            contestant_fills_++;
        }
    }

    // Record a cancel (called when cancel() succeeds or fails in live LOB)
    void on_cancel(uint64_t order_id, bool live_succeeded, int64_t tick_id) {
        std::lock_guard<std::mutex> lock(mu_);
        auto it = orders_.find(order_id);
        if (it == orders_.end()) {
            if (live_succeeded) {
                // Live LOB cancelled something shadow doesn't know about
                add_violation({ViolationType::STALE_CANCEL, tick_id, order_id,
                    "cancel of unknown order_id in shadow book"});
                penalty_cancel_ = std::min(W_CANCEL, penalty_cancel_ + PENALTY_PER_CANCEL);
            }
            return;
        }
        ShadowOrder& so = it->second;
        if (so.is_cancelled || so.is_fully_filled) {
            add_violation({ViolationType::STALE_CANCEL, tick_id, order_id,
                "cancel of already-closed order"});
            penalty_cancel_ = std::min(W_CANCEL, penalty_cancel_ + PENALTY_PER_CANCEL);
            return;
        }
        so.is_cancelled = true;
        _remove_from_level(order_id, so);
        orders_.erase(it);
        _update_best();
    }

    // Validate cash/position against GM's reported values at tick end
    void validate_contestant_state(int64_t reported_position, int64_t reported_cash_fp,
                                   int64_t tick_id) {
        std::lock_guard<std::mutex> lock(mu_);
        // Allow 1-cent tolerance for fixed-point rounding
        if (std::abs(shadow_position_ - reported_position) > 1) {
            add_violation({ViolationType::POSITION_INTEGRITY_MISMATCH, tick_id, 0,
                "shadow_pos=" + std::to_string(shadow_position_)
                + " reported=" + std::to_string(reported_position)});
        }
        // Cash tolerance: 1 cent
        __int128 cash_diff = shadow_cash_fp_ - reported_cash_fp;
        if (cash_diff < 0) cash_diff = -cash_diff;
        if (cash_diff > static_cast<__int128>(to_fp(0.01))) {
            add_violation({ViolationType::CASH_INTEGRITY_MISMATCH, tick_id, 0,
                "shadow_cash=" + fp_str(shadow_cash_fp_)
                + " reported=" + fp_str(reported_cash_fp)});
            penalty_cash_ = std::min(W_CASH, penalty_cash_ + PENALTY_PER_CASH);
        }
    }

    // ── Final correctness score (0.0 = invalid, 1.0 = perfect) ────────────
    double correctness_score() const {
        std::lock_guard<std::mutex> lock(mu_);
        double total_penalty = penalty_fifo_ + penalty_double_ + penalty_cancel_
                             + penalty_price_ + penalty_cash_;
        return std::max(0.0, 1.0 - total_penalty);
    }

    // ── Violation summary (for JSON output) ────────────────────────────────
    struct Summary {
        double   correctness_score;
        uint64_t total_violations;
        uint64_t fifo_violations;
        uint64_t double_fill_violations;
        uint64_t stale_cancel_violations;
        uint64_t price_violations;
        uint64_t cash_violations;
        int64_t  contestant_fills;
        std::vector<Violation> first_violations;  // first 10 of each type
    };

    Summary report() const {
        std::lock_guard<std::mutex> lock(mu_);
        Summary s{};
        s.correctness_score = std::max(0.0, 1.0 - penalty_fifo_ - penalty_double_
                                           - penalty_cancel_ - penalty_price_ - penalty_cash_);
        s.contestant_fills  = contestant_fills_;
        for (const auto& v : violations_) {
            s.total_violations++;
            switch (v.type) {
                case ViolationType::FIFO_PRIORITY_BREACH:     s.fifo_violations++;          break;
                case ViolationType::DOUBLE_FILL:              s.double_fill_violations++;    break;
                case ViolationType::STALE_CANCEL:             s.stale_cancel_violations++;   break;
                case ViolationType::FILL_PRICE_INVALID:       s.price_violations++;          break;
                case ViolationType::CASH_INTEGRITY_MISMATCH:
                case ViolationType::POSITION_INTEGRITY_MISMATCH: s.cash_violations++;       break;
            }
            if (s.first_violations.size() < 10) {
                s.first_violations.push_back(v);
            }
        }
        return s;
    }

    // Emit JSON report to stdout (appended after main result, for Go parser)
    void emit_json(std::ostream& out) const {
        auto s = report();
        out << ",\"correctness\":" << s.correctness_score
            << ",\"violations\":" << s.total_violations
            << ",\"fifo_violations\":" << s.fifo_violations
            << ",\"double_fill_violations\":" << s.double_fill_violations
            << ",\"stale_cancel_violations\":" << s.stale_cancel_violations
            << ",\"price_violations\":" << s.price_violations
            << ",\"cash_violations\":" << s.cash_violations
            << ",\"total_fills\":" << s.contestant_fills;
            
        out << ",\"first_violations\":[";
        for (size_t i = 0; i < s.first_violations.size(); ++i) {
            if (i > 0) out << ",";
            out << "{\"type\":" << static_cast<int>(s.first_violations[i].type)
                << ",\"tick_id\":" << s.first_violations[i].tick_id
                << ",\"order_id\":" << s.first_violations[i].order_id
                << ",\"detail\":\"" << s.first_violations[i].detail << "\"}";
        }
        out << "]";
    }

private:
    mutable std::mutex mu_;

    // Shadow book (mirrors live LOB exactly)
    std::map<int64_t, ShadowLevel, std::greater<int64_t>> bid_levels_;
    std::map<int64_t, ShadowLevel, std::less<int64_t>>    ask_levels_;
public:
    std::unordered_map<uint64_t, ShadowOrder>              orders_;

    uint64_t global_seq_      = 0;

public:
    // Violation log
    std::vector<Violation> violations_;
private:
    static constexpr size_t MAX_VIOLATIONS = 10'000;

    // Penalty accumulators (capped at weight)
    double penalty_fifo_   = 0.0;
    double penalty_double_ = 0.0;
    double penalty_cancel_ = 0.0;
    double penalty_price_  = 0.0;
    double penalty_cash_   = 0.0;

    void add_violation(Violation v) {
        if (violations_.size() < MAX_VIOLATIONS)
            violations_.push_back(std::move(v));
    }

    void _remove_from_level(uint64_t order_id, const ShadowOrder& so) {
        if (so.is_bid) {
            auto lit = bid_levels_.find(so.price_fp);
            if (lit == bid_levels_.end()) return;
            auto& level = lit->second;
            auto dit = std::find(level.order_ids.begin(), level.order_ids.end(), order_id);
            if (dit != level.order_ids.end()) {
                level.total_volume -= so.remaining_volume;
                level.order_ids.erase(dit);
            }
            if (level.total_volume <= 0 || level.order_ids.empty())
                bid_levels_.erase(lit);
        } else {
            auto lit = ask_levels_.find(so.price_fp);
            if (lit == ask_levels_.end()) return;
            auto& level = lit->second;
            auto dit = std::find(level.order_ids.begin(), level.order_ids.end(), order_id);
            if (dit != level.order_ids.end()) {
                level.total_volume -= so.remaining_volume;
                level.order_ids.erase(dit);
            }
            if (level.total_volume <= 0 || level.order_ids.empty())
                ask_levels_.erase(lit);
        }
    }

    void _update_best() {
        shadow_best_bid_ = bid_levels_.empty() ? 0        : bid_levels_.begin()->first;
        shadow_best_ask_ = ask_levels_.empty() ? INT64_MAX: ask_levels_.begin()->first;
    }

    static std::string fp_str(int64_t fp) {
        std::ostringstream ss;
        ss << (static_cast<double>(fp) / FIXED_POINT);
        return ss.str();
    }
};
