apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: vidhi_postgres:5432
    user: vidhi
    secureJsonData:
      password: vidhi_secret
    database: vidhidb
    jsonData:
      sslmode: disable
      timescaledb: true
