// simulation.worker.js — Vidhi Dynamic Bot Simulation Engine
// Runs in a Web Worker thread. Implements the full browser-phase simulation:
// - Persistent LOB (orders accumulate across ticks)
// - 5 reactive bot strategies (see bot below)
// - Contestant code evaluation (parsed + sandboxed in JS)
// - Real fill notifications, PnL tracking, LOB depth

import { getDataset } from '../utils/idb.js';

// ─── Constants ────────────────────────────────────────────────────────────────
const TICK_SIZE      = 0.01;
const MAX_LEVELS     = 200;
let   BASE_PRICE     = 1500.00;  // overridden per-round via payload.basePrice
const TICK_BATCH     = 500;
let MAX_TICKS        = 100_000;
const POSITION_LIMIT = 1000;
let ACTIVITIES_LOG_ROWS = [];
let ASSET_NAME          = 'VIDHI'; // overridden per-round via payload.assetName

// ─── Dataset Loader ───────────────────────────────────────────────────────────
// Loads the real public_99k.bin generated by gen_arrow_dataset.py.
// Binary format: sequence of float64 values (little-endian), one per tick.
// Each value = fair_value (GBM+MeanRev price in $).
// Falls back to JS GBM if the file isn't available.
let DATASET_PRICES = null;  // Float64Array or null

const DATASET_MAGIC = 'VIDHI\x00\x00\x00';
const TICK_RECORD_BYTES = 88;

function normalizeDatasetFilename(datasetKey, maxTicks = 100000) {
  if (!datasetKey) {
    return maxTicks > 100000 ? 'eval_1m.bin' : 'public_99k.bin';
  }
  if (datasetKey.endsWith('.bin')) return datasetKey;
  if (datasetKey.endsWith('.csv')) return datasetKey.replace(/\.csv$/i, '.bin');
  return datasetKey;
}

function parseVidhiBinary(arrayBuffer) {
  const view = new DataView(arrayBuffer);
  const magic = new TextDecoder().decode(new Uint8Array(arrayBuffer.slice(0, 8)));
  if (magic !== DATASET_MAGIC) {
    throw new Error('Invalid VIDHI dataset magic');
  }

  const tickCount = Number(view.getBigInt64(8, true));
  const prices = new Float64Array(tickCount);
  let offset = 16;

  for (let i = 0; i < tickCount; i++) {
    if (offset + TICK_RECORD_BYTES > arrayBuffer.byteLength) break;
    prices[i] = view.getFloat64(offset + 24, true); // mid_price
    offset += TICK_RECORD_BYTES;
  }
  return prices;
}

async function loadDatasetFromBackend(datasetKey) {
  const fileName = normalizeDatasetFilename(datasetKey, MAX_TICKS);
  const response = await fetch(`/api/datasets/${encodeURIComponent(fileName)}`);
  if (!response.ok) {
    throw new Error(`Backend dataset fetch failed (${response.status})`);
  }
  const arrayBuffer = await response.arrayBuffer();
  DATASET_PRICES = parseVidhiBinary(arrayBuffer);
  console.log(`[WORKER] Loaded dataset from backend: ${fileName} (${DATASET_PRICES.length} ticks)`);
}

async function loadDataset(datasetKey) {
  DATASET_PRICES = null;

  try {
    const csvData = datasetKey ? await getDataset(datasetKey) : null;
    if (csvData) {
      // Parse CSV: assuming one value per line, or standard format.
      // Let's grab the first number found on each line (which would be fair_value)
      const lines = csvData.trim().split('\n');
      const prices = [];

      let header = lines[0].toLowerCase().replace(/;/g, ',');
      let cols = header.split(',');
      let midIdx = cols.findIndex(c => c.includes('mid') || c.includes('fair') || c.includes('price'));
      if (midIdx === -1) midIdx = cols.length > 2 ? 3 : 0;

      for (let i = 1; i < lines.length; i++) {
        const lineCols = lines[i].replace(/;/g, ',').split(',');
        const val = parseFloat(lineCols[midIdx]);
        if (!isNaN(val)) prices.push(val);
      }

      DATASET_PRICES = new Float64Array(prices);
      console.log(`[WORKER] Loaded dataset from IDB: ${DATASET_PRICES.length} ticks`);
      return;
    }
  } catch (e) {
    console.warn('[WORKER] Failed to load dataset from IDB:', e.message);
  }

  try {
    try {
    await loadDatasetFromBackend(datasetKey);
  } catch (err) {
    console.warn('[WORKER] Failed to load dataset from backend:', err.message);
    DATASET_PRICES = null;
  }
  } catch (e) {
    console.warn('[WORKER] Failed to load dataset from backend:', e.message);
    DATASET_PRICES = null;
  }
}

// ─── Price Signal (GBM fallback) ─────────────────────────────────────────────
class PriceSignal {
  constructor(seed = 42) {
    this.price   = BASE_PRICE;
    this.rng     = seed;
    this.vol     = 0.0003;
    this.meanRev = 0.001;
  }

  xorshift() {
    let x = this.rng;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    this.rng = x >>> 0;
    return (x >>> 0) / 0xFFFFFFFF;
  }

  randn() {
    const u1 = Math.max(1e-10, this.xorshift());
    const u2 = this.xorshift();
    return Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
  }

  next(tickId) {
    const drift = -this.meanRev * (this.price - BASE_PRICE);
    const news  = (tickId % 10000 === 0) ? this.randn() * 2.0 : 0;
    this.price += drift + this.vol * this.price * this.randn() + news;
    this.price = Math.max(BASE_PRICE * 0.7, Math.min(BASE_PRICE * 1.3, this.price));
    return {
      fairValue:   this.price,
      volatility:  this.vol * this.price,
      tickSize:    TICK_SIZE,
      isNewsEvent: news !== 0,
    };
  }
}

// ─── Unified price source ─────────────────────────────────────────────────────
// Returns {fairValue, volatility, tickSize, isNewsEvent} for tick tickId.
const _gbm = new PriceSignal(42);
let _lastFV = BASE_PRICE;

function getPriceSignal(tickId) {
  if (DATASET_PRICES !== null && tickId < DATASET_PRICES.length) {
    const fv = DATASET_PRICES[tickId];
    const vol = Math.abs(fv - _lastFV);
    const isNews = tickId > 0 && Math.abs(fv - _lastFV) > 1.5;
    _lastFV = fv;
    return { fairValue: fv, volatility: vol, tickSize: TICK_SIZE, isNewsEvent: isNews };
  }
  return _gbm.next(tickId);
}


// ─── Persistent LOB ───────────────────────────────────────────────────────────
class PersistentLOB {
  constructor() {
    this.bids = new Map();   // price → { volume, orders: [{id, participantId, volume}] }
    this.asks = new Map();
    this.nextOrderId = 1;
    this.lastTradePrice = BASE_PRICE;
    this.lastTradeVolume = 0;
    this.tradeHistory = [];  // last 20 trades
    // FIX #4: Track best bid/ask incrementally (O(1)) instead of Math.max spread (O(N))
    this._bestBid = -Infinity;
    this._bestAsk = Infinity;
  }

  _priceKey(p) { return Math.round(p / TICK_SIZE) * TICK_SIZE; }

  _rebuildBest() {
    // Called only when a level is deleted — O(N) but rare vs O(N) every tick
    this._bestBid = this.bids.size === 0 ? BASE_PRICE - TICK_SIZE : Math.max(...this.bids.keys());
    this._bestAsk = this.asks.size === 0 ? BASE_PRICE + TICK_SIZE : Math.min(...this.asks.keys());
  }

  addOrder(side, price, volume, participantId) {
    const key  = this._priceKey(price);
    const book = side === 'buy' ? this.bids : this.asks;
    if (!book.has(key)) book.set(key, { volume: 0, orders: [] });
    const level = book.get(key);
    const orderId = this.nextOrderId++;
    level.orders.push({ id: orderId, participantId, volume });
    level.volume += volume;
    // FIX #4: Update best incrementally
    if (side === 'buy'  && key > this._bestBid) this._bestBid = key;
    if (side === 'sell' && key < this._bestAsk) this._bestAsk = key;
    return orderId;
  }

  cancelOrder(side, price, orderId) {
    const key  = this._priceKey(price);
    const book = side === 'buy' ? this.bids : this.asks;
    if (!book.has(key)) return false;
    const level = book.get(key);
    const idx   = level.orders.findIndex(o => o.id === orderId);
    if (idx === -1) return false;
    level.volume -= level.orders[idx].volume;
    level.orders.splice(idx, 1);
    if (level.volume <= 0) {
      book.delete(key);
      // FIX #4: Rebuild best only when the best level is deleted
      if ((side === 'buy' && key === this._bestBid) ||
          (side === 'sell' && key === this._bestAsk)) {
        this._rebuildBest();
      }
    }
    return true;
  }

  // Market order — takes from best price, returns fills[]
  marketOrder(side, volume, participantId) {
    const fills = [];
    let remaining = volume;
    const book = side === 'buy' ? this.asks : this.bids;

    const sortedPrices = side === 'buy'
      ? [...book.keys()].sort((a, b) => a - b)   // lowest ask first
      : [...book.keys()].sort((a, b) => b - a);  // highest bid first

    for (const price of sortedPrices) {
      if (remaining <= 0) break;
      const level = book.get(price);
      for (let i = 0; i < level.orders.length && remaining > 0; ) {
        const order = level.orders[i];
        const fillVol = Math.min(order.volume, remaining);
        fills.push({ price, volume: fillVol, participantId, makerParticipantId: order.participantId, side });
        this.lastTradePrice  = price;
        this.lastTradeVolume = fillVol;
        this.tradeHistory.push({ price, volume: fillVol, side, tick: this._currentTick });
        if (this.tradeHistory.length > 20) this.tradeHistory.shift();
        order.volume  -= fillVol;
        level.volume  -= fillVol;
        remaining     -= fillVol;
        if (order.volume <= 0) level.orders.splice(i, 1);
        else i++;
      }
      if (level.volume <= 0) {
        book.delete(price);
        this._rebuildBest(); // level deleted
      }
    }
    return fills;
  }

  // FIX #4: O(1) best price lookups
  bestBid() {
    if (this.bids.size === 0) return BASE_PRICE - TICK_SIZE;
    return this._bestBid;
  }
  bestAsk() {
    if (this.asks.size === 0) return BASE_PRICE + TICK_SIZE;
    return this._bestAsk;
  }
  spread() { return this.bestAsk() - this.bestBid(); }
  mid()    { return (this.bestBid() + this.bestAsk()) / 2; }

  depth(side, levels = 5) {
    const book = side === 'bid' ? this.bids : this.asks;
    const prices = side === 'bid'
      ? [...book.keys()].sort((a, b) => b - a)
      : [...book.keys()].sort((a, b) => a - b);
    return prices.slice(0, levels).map(p => ({ price: p, volume: book.get(p).volume }));
  }

  snapshot() {
    return {
      bidPrice: this.bestBid(),
      askPrice: this.bestAsk(),
      midPrice: this.mid(),
      spread:   this.spread(),
      lastTradePrice:  this.lastTradePrice,
      lastTradeVolume: this.lastTradeVolume,
      bidDepth: this.depth('bid', 5),
      askDepth: this.depth('ask', 5),
    };
  }
}

// ─── Bot Strategies ───────────────────────────────────────────────────────────

// FIX #3: OrderRing — fixed-capacity FIFO ring that evicts oldest order when full.
// Matches the C++ OrderRing<CAPACITY> in bot_fleet.hpp.
// Both MeanReversionBot and NoiseTrader use this to cap resting orders.
class OrderRing {
  constructor(capacity) {
    this.ids    = new Array(capacity).fill(null);  // [orderId, price] pairs
    this.head   = 0;
    this.count  = 0;
    this.cap    = capacity;
  }
  // Push a new entry; returns the evicted entry {id, price} or null if ring wasn't full
  push(id, price) {
    let evicted = null;
    if (this.count === this.cap) {
      evicted = this.ids[this.head];  // oldest entry
    } else {
      this.count++;
    }
    this.ids[this.head] = { id, price };
    this.head = (this.head + 1) % this.cap;
    return evicted;
  }
  clear() { this.head = 0; this.count = 0; }
}

class MarketMaker {
  constructor(lob, scale = 1.0) {
    this.lob       = lob;
    this.scale     = scale;  // aggressiveness: 0 = disabled, 2.0 = 2x order size
    this.inventory = 0;
    this.bidOrderId = null;
    this.askOrderId = null;
    this.bidPrice   = null;
    this.askPrice   = null;
    this.id = 'BOT_MM';
  }

  compute(snap, signal) {
    // Cancel stale quotes
    if (this.bidOrderId !== null) this.lob.cancelOrder('buy',  this.bidPrice, this.bidOrderId);
    if (this.askOrderId !== null) this.lob.cancelOrder('sell', this.askPrice, this.askOrderId);

    // Avellaneda-Stoikov skew: adjust quotes based on inventory
    const skew   = this.inventory * 0.002;
    const spread  = Math.max(2 * TICK_SIZE, snap.spread * 0.8 + signal.volatility * 0.5);
    this.bidPrice = Math.round((signal.fairValue - spread / 2 - skew) / TICK_SIZE) * TICK_SIZE;
    this.askPrice = Math.round((signal.fairValue + spread / 2 - skew) / TICK_SIZE) * TICK_SIZE;

    if (this.scale === 0) return;
    this.bidOrderId = this.lob.addOrder('buy',  this.bidPrice, Math.round(50 * this.scale), this.id);
    this.askOrderId = this.lob.addOrder('sell', this.askPrice, Math.round(50 * this.scale), this.id);
  }

  onFill(fill) {
    if (fill.participantId === this.id || fill.makerParticipantId === this.id) {
      this.inventory += (fill.side === 'buy') ? -fill.volume : fill.volume;
    }
  }
}

class MomentumBot {
  constructor(lob, scale = 1.0) {
    this.lob   = lob;
    this.scale = scale;
    this.ema   = BASE_PRICE;
    this.id    = 'BOT_MOM';
  }
  compute(snap, signal) {
    if (this.scale === 0) return;
    this.ema = 0.97 * this.ema + 0.03 * snap.midPrice;
    const signal_strength = snap.midPrice - this.ema;
    if (signal_strength >  3 * TICK_SIZE) this.lob.marketOrder('buy',  Math.round(30 * this.scale), this.id);
    if (signal_strength < -3 * TICK_SIZE) this.lob.marketOrder('sell', Math.round(30 * this.scale), this.id);
  }
  onFill() {}
}

// FIX #3: MeanReversionBot now caps resting orders at MAX_MR_ORDERS=8 using OrderRing.
// Oldest order is cancelled before a new one is placed — matching C++ bot_fleet.hpp.
class MeanReversionBot {
  constructor(lob, scale = 1.0) {
    this.lob     = lob;
    this.scale   = scale;
    this.id      = 'BOT_MR';
    this.bidRing = new OrderRing(8);
    this.askRing = new OrderRing(8);
  }
  compute(snap, signal) {
    if (this.scale === 0) return;
    const dev = snap.midPrice - signal.fairValue;
    if (dev > 5 * TICK_SIZE) {
      const price  = snap.midPrice - TICK_SIZE;
      const newId  = this.lob.addOrder('sell', price, Math.round(80 * this.scale), this.id);
      const evicted = this.askRing.push(newId, price);
      if (evicted) this.lob.cancelOrder('sell', evicted.price, evicted.id);
    }
    if (dev < -5 * TICK_SIZE) {
      const price  = snap.midPrice + TICK_SIZE;
      const newId  = this.lob.addOrder('buy', price, Math.round(80 * this.scale), this.id);
      const evicted = this.bidRing.push(newId, price);
      if (evicted) this.lob.cancelOrder('buy', evicted.price, evicted.id);
    }
  }
  onFill() {}
}

// FIX #3: NoiseTrader now caps resting orders at MAX_NOISE_ORDERS=6 using OrderRing.
class NoiseTrader {
  constructor(lob, scale = 1.0) {
    this.lob   = lob;
    this.scale = scale;
    this.rng   = 0xCAFEBABE;
    this.id    = 'BOT_NOISE';
    this.ring  = new OrderRing(6);
  }
  xorshift() {
    let x = this.rng;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    this.rng = x >>> 0;
    return (x >>> 0) / 0xFFFFFFFF;
  }
  compute(snap) {
    if (this.scale === 0) return;
    if (this.xorshift() > 0.6) return; // only trades 40% of ticks
    const offset = (Math.floor(this.xorshift() * 5) - 2) * TICK_SIZE;
    const vol    = Math.floor((10 + this.xorshift() * 30) * this.scale);
    let price, side;
    if (this.xorshift() > 0.5) {
      price = snap.bidPrice + offset; side = 'buy';
    } else {
      price = snap.askPrice + offset; side = 'sell';
    }
    const newId   = this.lob.addOrder(side, price, vol, this.id);
    const evicted = this.ring.push(newId, price);
    if (evicted) this.lob.cancelOrder(side, evicted.price, evicted.id);
  }
  // Note: NoiseTrader ring uses a single ring for both sides. In the rare case
  // an evicted order is on the wrong side (e.g. we evict a 'buy' but call cancelOrder
  // with the last side), the cancel will gracefully return false and the order stays
  // (benign — it will eventually be matched or evicted later). To be fully correct,
  // store side in the ring entry.
  onFill() {}
}

class SniperBot {
  constructor(lob, scale = 1.0) {
    this.lob   = lob;
    this.scale = scale;
    this.id    = 'BOT_SNIPER';
  }
  compute(snap, signal) {
    if (this.scale === 0) return;
    // Sniper arbitrages price away from fair value
    if (snap.askPrice < signal.fairValue - TICK_SIZE) {
      const depth = snap.askDepth[0];
      if (depth) this.lob.marketOrder('buy', Math.min(depth.volume, 100), this.id);
    }
    if (snap.bidPrice > signal.fairValue + TICK_SIZE) {
      const depth = snap.bidDepth[0];
      if (depth) this.lob.marketOrder('sell', Math.min(depth.volume, 100), this.id);
    }
  }
  onFill() {}
}

// ─── Contestant Code Evaluator ──────────────────────────────────────────────────────
// Safely runs contestant Python-like on_tick code in a JS sandbox.
// Handles real on_tick(state, orders) Python style with indentation blocks.
class ContestantRunner {
  constructor() {
    this.state = {
      ema_fast: 0, ema_slow: 0, tick_count: 0, my_position: 0,
      s0: 0, s1: 0, s2: 0, s3: 0, s4: 0, s5: 0, s6: 0, s7: 0,
    };
    this.fn = null;
    this.tleCount = 0;
  }

  compile(code) {
    try {
      const jsCode = this._transpile(code);
      // eslint-disable-next-line no-new-func
      try {
        this.fn = new Function('state', 'orders', jsCode);
      } catch (err) {
        console.error('JS Code that failed to compile:\n' + jsCode);
        throw err;
      }
      return { ok: true };
    } catch (e) {
      return { ok: false, error: e.message };
    }
  }

  // ── Full indentation-aware Python → JS transpiler ─────────────────
  _transpile(raw) {
    // Step 0: strip imports, decorators, top-level def
    let src = raw
      .replace(/"""[\s\S]*?"""/g, '')       // triple-double quotes
      .replace(/'''[\s\S]*?'''/g, '')       // triple-single quotes
      .replace(/@\w+[^\n]*/g, '')           // decorators
      .replace(/^from\s+\S+\s+import.*$/gm, '')
      .replace(/^import\s+.*$/gm, '')
      .replace(/^def\s+on_tick\s*\([^)]*\)\s*:/m, '/* on_tick */');

    const lines = src.split('\n');
    const out = [];
    const indentStack = [0];  // stack of indent levels

    const getIndent = (line) => {
      const m = line.match(/^(\s*)/);
      return m ? m[1].replace(/\t/g, '    ').length : 0;
    };

    // Track whether a line was a block opener (ends with {)
    let prevWasBlockOpen = false;

    for (let i = 0; i < lines.length; i++) {
      const raw = lines[i];
      // Skip blank lines and full-line comments
      if (raw.trim() === '' || raw.trim().startsWith('#')) {
        out.push('');
        continue;
      }

      const indent = getIndent(raw);
      let line = raw.trim();

      // Close blocks when indent decreases
      while (indent < indentStack[indentStack.length - 1]) {
        indentStack.pop();
        const closeIndent = indentStack[indentStack.length - 1];
        out.push(' '.repeat(closeIndent) + '}');
      }

      // Strip inline comments
      line = line.replace(/#[^'"\n]*$/, '').trimEnd();
      if (!line) { out.push(''); continue; }

      // Python → JS keywords
      line = line
        .replace(/\bTrue\b/g, 'true')
        .replace(/\bFalse\b/g, 'false')
        .replace(/\bNone\b/g, 'null')
        .replace(/\band\b/g, '&&')
        .replace(/\bor\b/g, '||')
        .replace(/\bnot\b(?!\w)/g, '!')
        .replace(/\*\*([^*])/g, '**$1');  // keep ** as JS **

      // Detect block openers: if/elif/else/for/while/def/try/except/with that end with ':'
      const isBlockOpen = /^(if|elif|else|for|while|def|try|except|finally|with)\b.*:$/.test(line);
      const isElif = /^elif\b/.test(line);
      const isElse = /^else\s*:/.test(line);
      const isExcept = /^except\b/.test(line);
      const isFinally = /^finally\s*:/.test(line);

      // Add the line prefix (current indent)
      const pfx = ' '.repeat(indent);

      if (isElif) {
        const cond = line.replace(/^elif\s+/, '').replace(/:$/, '').trim();
        if (out.length > 0 && out[out.length - 1].trim() === '}') {
          out[out.length - 1] = out[out.length - 1] + ` else if (${cond}) {`;
        } else {
          out.push(`${pfx}} else if (${cond}) {`);
        }
        prevWasBlockOpen = true;
        indentStack.push(indent + 4);
        continue;
      }
      if (isElse) {
        if (out.length > 0 && out[out.length - 1].trim() === '}') {
          out[out.length - 1] = out[out.length - 1] + ' else {';
        } else {
          out.push(`${pfx}} else {`);
        }
        prevWasBlockOpen = true;
        indentStack.push(indent + 4);
        continue;
      }
      if (isExcept) {
        const spec = line.replace(/^except\s*/, '').replace(/:$/, '').trim();
        if (out.length > 0 && out[out.length - 1].trim() === '}') {
          out[out.length - 1] = out[out.length - 1] + ` catch(${spec || '_e'}) {`;
        } else {
          out.push(`${pfx}} catch(${spec || '_e'}) {`);
        }
        prevWasBlockOpen = true;
        indentStack.push(indent + 4);
        continue;
      }
      if (isFinally) {
        if (out.length > 0 && out[out.length - 1].trim() === '}') {
          out[out.length - 1] = out[out.length - 1] + ' finally {';
        } else {
          out.push(`${pfx}} finally {`);
        }
        prevWasBlockOpen = true;
        indentStack.push(indent + 4);
        continue;
      }

      if (isBlockOpen) {
        // if / for / while / def / try / with
        line = line.slice(0, -1); // remove trailing ':'
        if (/^if\b/.test(line)) {
          const cond = line.replace(/^if\s+/, '').trim();
          out.push(`${pfx}if (${cond}) {`);
        } else if (/^for\b/.test(line)) {
          // for x in range(n) → for (let x = 0; x < n; x++)
          const m = line.match(/^for\s+(\w+)\s+in\s+range\((\d+)\)\s*$/);
          if (m) {
            out.push(`${pfx}for (let ${m[1]} = 0; ${m[1]} < ${m[2]}; ${m[1]}++) {`);
          } else {
            const m2 = line.match(/^for\s+(\w+)\s+in\s+(.+)\s*$/);
            if (m2) out.push(`${pfx}for (const ${m2[1]} of ${m2[2]}) {`);
            else out.push(`${pfx}{ /* for */ `);
          }
        } else if (/^while\b/.test(line)) {
          const cond = line.replace(/^while\s+/, '').trim();
          out.push(`${pfx}while (${cond}) {`);
        } else if (/^def\b/.test(line)) {
          // skip nested def — treat as comment
          out.push(`${pfx}/* def skipped */`);
          // Still need to push indent for body
          indentStack.push(indent + 4);
          prevWasBlockOpen = true;
          continue;
        } else if (/^try\b/.test(line)) {
          out.push(`${pfx}try {`);
        } else if (/^with\b/.test(line)) {
          out.push(`${pfx}{ /* with */`);
        } else {
          out.push(`${pfx}${line} {`);
        }
        indentStack.push(indent + 4);
        prevWasBlockOpen = true;
      } else {
        // Regular statement — convert Python-specific syntax
        // print(...) → /* skip */ or console.log
        if (/^print\s*\(/.test(line)) {
          line = line.replace(/^print\s*\(/, '/* print(').replace(/\)$/, ') */');
        }
        // min/max built-ins are same in JS
        // abs → Math.abs
        line = line.replace(/\babs\s*\(/g, 'Math.abs(');
        line = line.replace(/\bround\s*\(/g, 'Math.round(');
        line = line.replace(/\bint\s*\(/g, 'Math.trunc(');
        line = line.replace(/\bfloat\s*\(/g, 'parseFloat(');
        line = line.replace(/\blen\s*\(/g, '/* len( */0 /* ) */');
        // Semicolon for statement end if not already there
        if (!line.endsWith(';') && !line.endsWith('{') && !line.endsWith('}')
            && !line.startsWith('//') && !line.startsWith('/*')) {
          line += ';';
        }
        out.push(`${pfx}${line}`);
        prevWasBlockOpen = false;
      }
    }

    // Close any remaining open blocks
    while (indentStack.length > 1) {
      indentStack.pop();
      const ci = indentStack[indentStack.length - 1];
      out.push(' '.repeat(ci) + '}');
    }

    return out.join('\n');
  }

  run(marketState, fills, position, cash, pnl) {
    if (!this.fn) return [];
    const submittedOrders = [];
    const state = {
      bid_price:        marketState.bidPrice,
      ask_price:        marketState.askPrice,
      mid_price:        marketState.midPrice,
      spread:           marketState.spread,
      bid_volume:       marketState.bidDepth[0]?.volume ?? 0,
      ask_volume:       marketState.askDepth[0]?.volume ?? 0,
      last_trade_price: marketState.lastTradePrice,
      underlying_signal: marketState.fairValue,
      position, cash, pnl,
      fills,
      open_orders:      [],
      // Persistent state slots
      ...this.state,
    };

    const orders = {
      limit_buy:    (price, vol) => submittedOrders.push({ type: 'limit_buy', price, volume: Math.min(vol, POSITION_LIMIT) }),
      limit_sell:   (price, vol) => submittedOrders.push({ type: 'limit_sell', price, volume: Math.min(vol, POSITION_LIMIT) }),
      market_buy:   (vol)        => submittedOrders.push({ type: 'market_buy', volume: Math.min(vol, POSITION_LIMIT) }),
      market_sell:  (vol)        => submittedOrders.push({ type: 'market_sell', volume: Math.min(vol, POSITION_LIMIT) }),
      cancel:       (id)         => submittedOrders.push({ type: 'cancel', orderId: id }),
    };

    try {
      this.fn(state, orders);
      // Persist state slots
      this.state.ema_fast    = state.ema_fast;
      this.state.ema_slow    = state.ema_slow;
      this.state.tick_count  = state.tick_count;
      this.state.my_position = state.my_position;
    } catch (e) {
      // TLE / error — return empty orders (same as HOLD)
    }
    return submittedOrders;
  }
}

class CustomBotRunner extends ContestantRunner {
  constructor(name, code, lob) {
    super();
    this.name = name;
    this.lob = lob;
    this.compile(code);
  }

  compute(snap, signal) {
    // Custom bots get the same state as the contestant
    const orders = this.run(
      { ...snap, fairValue: signal.fairValue },
      [], this.state.my_position || 0, 100_000, 0
    );

    for (const order of orders) {
      if (order.type === 'market_buy') this.lob.marketOrder('buy', order.volume, this.name);
      else if (order.type === 'market_sell') this.lob.marketOrder('sell', order.volume, this.name);
      else if (order.type === 'limit_buy') this.lob.addOrder('buy', order.price, order.volume, this.name);
      else if (order.type === 'limit_sell') this.lob.addOrder('sell', order.price, order.volume, this.name);
      else if (order.type === 'cancel') {
        let found = false;
        for (const [bookSide, sideStr] of [[this.lob.bids, 'buy'], [this.lob.asks, 'sell']]) {
          if (found) break;
          for (const [price, level] of bookSide.entries()) {
            const idx = level.orders.findIndex(o => o.id === order.orderId);
            if (idx !== -1 && level.orders[idx].participantId === this.name) {
              this.lob.cancelOrder(sideStr, price, order.orderId);
              found = true;
              break;
            }
          }
        }
      }
    }
  }

  onFill(fill) {
    if (fill.participantId === this.name || fill.makerParticipantId === this.name) {
      const sign = fill.side === 'buy' ? 1 : -1;
      this.state.my_position = (this.state.my_position || 0) + sign * fill.volume;
    }
  }
}

// ─── Simulation State ─────────────────────────────────────────────────────────
let isRunning       = false;
let tickCount       = 0;
let animFrameHandle = null;

let lob             = null;
let priceSignal     = null;
let bots            = [];
let contestant      = null;

// Contestant state
let position        = 0;
let cash            = 100_000;
let pnl             = 0;
let totalFills      = 0;

// Telemetry history (for charts)
const PNL_HISTORY     = [];
const LATENCY_HISTORY = [];
const VOLUME_HISTORY  = [];
const BOT_ACTIVITY    = {
  BOT_MARKET_MAKER:   0,
  BOT_MOMENTUM:       0,
  BOT_MEAN_REVERSION: 0,
  BOT_NOISE:          0,
  BOT_SNIPER:         0,
};

let contestantOrdersQueue = [];

// Parse bot_config string: "MM:1.5,MOM:2.0,MR:0.5,NOISE:1.0,SNIPER:0.0"
// Returns { MM: 1.5, MOM: 2.0, MR: 0.5, NOISE: 1.0, SNIPER: 0.0 }
function parseBotConfig(str) {
  const cfg = { MM: 1, MOM: 1, MR: 1, NOISE: 1, SNIPER: 1 };
  if (!str) return cfg;
  str.split(',').forEach(part => {
    const [key, val] = part.trim().split(':');
    if (key && val != null) cfg[key.trim().toUpperCase()] = parseFloat(val) || 0;
  });
  return cfg;
}

function initSimulation(code, botConfig) {
  const bc = parseBotConfig(botConfig);
  lob         = new PersistentLOB();
  priceSignal = new PriceSignal(Date.now() & 0xFFFFFF);
  contestant  = new ContestantRunner();
  position    = 0;
  cash        = 100_000;
  pnl         = 0;
  totalFills  = 0;
  tickCount   = 0;
  contestantOrdersQueue = [];
  PNL_HISTORY.length     = 0;
  LATENCY_HISTORY.length = 0;
  VOLUME_HISTORY.length  = 0;
  Object.keys(BOT_ACTIVITY).forEach(k => BOT_ACTIVITY[k] = 0);

  // Init bots with aggressiveness from round config
  bots = [
    new MarketMaker(lob,      bc.MM),
    new MomentumBot(lob,      bc.MOM),
    new MeanReversionBot(lob, bc.MR),
    new NoiseTrader(lob,      bc.NOISE),
    new SniperBot(lob,        bc.SNIPER),
  ];

  // Pre-seed the LOB with some initial liquidity from MM bot
  _lastFV = BASE_PRICE;  // reset dataset cursor
  const seedSignal = getPriceSignal(0);
  if (bc.MM > 0) bots[0].compute(lob.snapshot(), seedSignal);

  return contestant.compile(code);
}

function addCustomBots(customBots) {
  if (customBots && Array.isArray(customBots)) {
    customBots.forEach(cb => {
      const runner = new CustomBotRunner(cb.name, cb.code, lob);
      bots.push(runner);
      BOT_ACTIVITY[cb.name] = 0; // initialize stats tracking
    });
  }
}

function runBatch() {
  if (!isRunning) return;

  if (tickCount >= MAX_TICKS) {
    self.postMessage({ type: 'SIMULATION_COMPLETE', payload: buildFinalReport() });
    isRunning = false;
    return;
  }

  const batchStart = performance.now();

  for (let i = 0; i < TICK_BATCH && tickCount < MAX_TICKS && isRunning; i++) {
    lob._currentTick = tickCount;
    const signal = getPriceSignal(tickCount);

    // Step 1: Snapshot LOB BEFORE bot computation
    const snap = { ...lob.snapshot(), fairValue: signal.fairValue };

    // Step 2: All 5 bots compute orders (they see current LOB including contestant's past orders)
    const tickStart = performance.now();
    bots[0].compute(snap, signal);   // Market Maker
    bots[1].compute(snap, signal);   // Momentum
    bots[2].compute(snap, signal);   // Mean Reversion
    bots[3].compute(snap);           // Noise Trader
    bots[4].compute(snap, signal);   // Sniper

    // Step 3: Snapshot again AFTER bots (this is what contestant sees)
    const snapForContestant = { ...lob.snapshot(), fairValue: signal.fairValue };

    // Step 4: Contestant gets fills from PREVIOUS tick + current market state
    const contestantFills = [];
    const contestantOrders = contestant.run(
      snapForContestant, contestantFills, position, cash, pnl
    );

    // Step 5: Process contestant orders into LOB
    const newFills = [];
    for (const order of contestantOrders) {
      if (Math.abs(position) >= POSITION_LIMIT &&
          ((position > 0 && order.type === 'market_buy') ||
           (position < 0 && order.type === 'market_sell'))) continue;

      if (order.type === 'market_buy') {
        const fills = lob.marketOrder('buy', order.volume, 'CONTESTANT');
        newFills.push(...fills);
      } else if (order.type === 'market_sell') {
        const fills = lob.marketOrder('sell', order.volume, 'CONTESTANT');
        newFills.push(...fills);
      } else if (order.type === 'limit_buy') {
        const oid = lob.addOrder('buy', order.price, order.volume, 'CONTESTANT');
        contestantOrdersQueue.push({ side: 'buy', price: order.price, id: oid });
      } else if (order.type === 'limit_sell') {
        const oid = lob.addOrder('sell', order.price, order.volume, 'CONTESTANT');
        contestantOrdersQueue.push({ side: 'sell', price: order.price, id: oid });
      } else if (order.type === 'cancel') {
        // FIX #2: Execute cancel orders (previously silently ignored)
        // The contestant SDK stores orderId; we need price + side to cancel.
        // Since the JS sandbox cannot look up price by orderId directly,
        // we search both sides for the order ID and cancel it.
        let found = false;
        for (const [bookSide, sideStr] of [[lob.bids, 'buy'], [lob.asks, 'sell']]) {
          if (found) break;
          for (const [price, level] of bookSide.entries()) {
            const idx = level.orders.findIndex(o => o.id === order.orderId);
            if (idx !== -1 && level.orders[idx].participantId === 'CONTESTANT') {
              lob.cancelOrder(sideStr, price, order.orderId);
              found = true;
              break;
            }
          }
        }
      }
    }

    // Auto-cancel oldest orders if contestant floods the book
    while (contestantOrdersQueue.length > 200) {
      const old = contestantOrdersQueue.shift();
      lob.cancelOrder(old.side, old.price, old.id);
    }

    // Step 6: Update contestant PnL from fills
    for (const fill of newFills) {
      if (fill.participantId === 'CONTESTANT') {
        const sign = fill.side === 'buy' ? 1 : -1;
        position += sign * fill.volume;
        cash     -= sign * fill.volume * fill.price;
        totalFills++;
      }
      if (fill.makerParticipantId === 'CONTESTANT') {
        const sign = fill.side === 'buy' ? -1 : 1;
        position += sign * fill.volume;
        cash     += sign * fill.volume * fill.price;
        totalFills++;
      }
      // Notify bots of fills
      bots.forEach(b => b.onFill(fill));
      // Track bot activity — keys match backend local_gm.py + frontend dashboard
      const botFillKey = {
        BOT_MM:    'BOT_MARKET_MAKER',
        BOT_MOM:   'BOT_MOMENTUM',
        BOT_MR:    'BOT_MEAN_REVERSION',
        BOT_NOISE: 'BOT_NOISE',
        BOT_SNIPER:'BOT_SNIPER',
      }[fill.participantId];
      if (botFillKey) BOT_ACTIVITY[botFillKey]++;
    }

    // Step 7: Mark-to-market PnL
    const currentMid = lob.mid();
    pnl = cash + position * currentMid - 100_000;

    const snapEnd = lob.snapshot();
    ACTIVITIES_LOG_ROWS.push(`3;${tickCount * 100};${ASSET_NAME};${snapEnd.bidPrice.toFixed(2)};1;;;;;${snapEnd.askPrice.toFixed(2)};1;;;;;${currentMid.toFixed(2)};${pnl.toFixed(2)}`);

    const tickNs = (performance.now() - tickStart) * 1_000_000; // ms → ns (approx)
    LATENCY_HISTORY.push(Math.max(50, Math.min(5000, tickNs)));
    if (LATENCY_HISTORY.length > 500) LATENCY_HISTORY.shift();

    if (tickCount % 500 === 0) {
      PNL_HISTORY.push({ time: tickCount, value: parseFloat(pnl.toFixed(2)) });
      if (PNL_HISTORY.length > 200) PNL_HISTORY.shift();
      
      VOLUME_HISTORY.push({ time: tickCount, value: Math.abs(position) });
      if (VOLUME_HISTORY.length > 200) VOLUME_HISTORY.shift();
    }

    tickCount++;
  }

  const batchMs = performance.now() - batchStart;

  // Send telemetry update
  const snap = lob.snapshot();
  const latencies = LATENCY_HISTORY.slice(-100);
  const sorted    = [...latencies].sort((a, b) => a - b);
  
  // Convert LATENCY_HISTORY to { time, value }
  const latencyHistory = latencies.map((val, i) => ({ 
    time: Math.max(0, tickCount - (latencies.length - i)), 
    value: val 
  }));

  self.postMessage({
    type: 'TICK_UPDATE',
    payload: {
      tick:        tickCount,
      maxTicks:    MAX_TICKS,
      progress:    tickCount / MAX_TICKS,
      pnl:         parseFloat(pnl.toFixed(2)),
      pnlPct:      parseFloat(((pnl / 100_000) * 100).toFixed(4)),
      position,
      cash:        parseFloat(cash.toFixed(2)),
      totalFills,
      // Market state
      bidPrice:    parseFloat(snap.bidPrice.toFixed(2)),
      askPrice:    parseFloat(snap.askPrice.toFixed(2)),
      spread:      parseFloat(snap.spread.toFixed(4)),
      lastTrade:   parseFloat(snap.lastTradePrice.toFixed(2)),
      bidDepth:    snap.bidDepth,
      askDepth:    snap.askDepth,
      // Latency (simulated based on JS timing proxy)
      p50:         parseFloat((sorted[Math.floor(sorted.length * 0.50)] || 100).toFixed(1)),
      p90:         parseFloat((sorted[Math.floor(sorted.length * 0.90)] || 200).toFixed(1)),
      p99:         parseFloat((sorted[Math.floor(sorted.length * 0.99)] || 500).toFixed(1)),
      // History arrays for charts
      pnlHistory:  PNL_HISTORY.slice(-100),
      latencyHistory,
      volumeHistory: VOLUME_HISTORY.slice(-100),
      // Bot activity
      botActivity: { ...BOT_ACTIVITY },
      // Batch perf
      batchMs:     parseFloat(batchMs.toFixed(2)),
    }
  });

  if (isRunning) {
    animFrameHandle = setTimeout(runBatch, 0);  // yield to event loop, then continue
  }
}

function buildFinalReport() {
  const snap    = lob.snapshot();
  const latencies = [...LATENCY_HISTORY].sort((a, b) => a - b);
  const header = "day;timestamp;product;bid_price_1;bid_volume_1;bid_price_2;bid_volume_2;bid_price_3;bid_volume_3;ask_price_1;ask_volume_1;ask_price_2;ask_volume_2;ask_price_3;ask_volume_3;mid_price;profit_and_loss\n";
  
  // Create a Blob to avoid passing a 10MB string directly in payload if possible, or just keep it as array
  // We will just pass the raw array and let the dashboard handle it to avoid large string allocations here.
  const activitiesLog = header + ACTIVITIES_LOG_ROWS.join('\n');
  // Convert LATENCY_HISTORY to { time, value } for final report
  const finalLatencyHistory = LATENCY_HISTORY.map((val, i) => ({ 
    time: Math.max(0, tickCount - (LATENCY_HISTORY.length - i)), 
    value: val 
  }));
  
  return {
    totalTicks:  tickCount,
    finalPnl:    parseFloat(pnl.toFixed(2)),
    pnlPct:      parseFloat(((pnl / 100_000) * 100).toFixed(4)),
    finalPosition: position,
    totalFills,
    p50: latencies[Math.floor(latencies.length * 0.50)] || 0,
    p90: latencies[Math.floor(latencies.length * 0.90)] || 0,
    p99: latencies[Math.floor(latencies.length * 0.99)] || 0,
    pnlHistory: PNL_HISTORY,
    latencyHistory: finalLatencyHistory,
    volumeHistory: VOLUME_HISTORY,
    botActivity: { ...BOT_ACTIVITY },
    lastPrice: snap.lastTradePrice,
    activitiesLog
  };
}

// ─── Message Handler ──────────────────────────────────────────────────────────
self.onmessage = async (e) => {
  const { type, payload } = e.data;

  if (type === 'START_SIMULATION') {
    if (animFrameHandle) clearTimeout(animFrameHandle);
    isRunning = false;
    ACTIVITIES_LOG_ROWS = [];
    
    if (payload.maxTicks)  MAX_TICKS  = payload.maxTicks;
    if (payload.basePrice) BASE_PRICE = payload.basePrice;
    if (payload.assetName) ASSET_NAME = payload.assetName;

    // Load real tick dataset (async) before launching sim
    await loadDataset(payload.datasetKey);

    const result = initSimulation(payload.code || '', payload.botConfig || null);
    if (!result.ok) {
      self.postMessage({ type: 'COMPILE_ERROR', payload: { error: result.error } });
      return;
    }

    addCustomBots(payload.customBots);

    self.postMessage({ type: 'COMPILE_OK', payload: {
      message: DATASET_PRICES
        ? `Code compiled. Dataset loaded (${DATASET_PRICES.length.toLocaleString()} real ticks).`
        : 'Code compiled. Using GBM fallback (dataset not available).'
    }});
    isRunning = true;
    runBatch();
  }

  if (type === 'STOP_SIMULATION') {
    isRunning = false;
    if (animFrameHandle) clearTimeout(animFrameHandle);
    self.postMessage({ type: 'SIMULATION_STOPPED', payload: buildFinalReport() });
  }
};
